name: Build and Push Docker Image
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Increment version
        run: |
          # Increment version number (e.g., semantic versioning)
          version=$(awk -F. '{$NF = $NF + 1;} 1' OFS=. version.txt)
          echo "New version: $version"
          echo "$version" > version.txt
 
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t your-image-name:${{ cat version.txt }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push your-image-name:${{ cat version.txt }}
